### ISSUE TITLE
Перепеши на питон, прост лень на пк всё делать 

### ISSUE THREAD

**Issue by crceck123** [xeondev1337/OpenBrawl#12]
бот

**Comment by BreadBSS** [comment]
ты че еблан

**Comment by crceck123** [comment]
> ты че еблан

ты

**Comment by TheAcelot** [comment]
либо ты бомж без пк либо ты лох

**Comment by crceck123** [comment]
> либо ты бомж без пк либо ты лох

Ты

**Comment by TheAcelot** [comment]
> > либо ты бомж без пк либо ты лох
> 
> Ты

мобильный лох

**Comment by crceck123** [comment]
> > > либо ты бомж без пк либо ты лох
> > 
> > 
> > Ты
> 
> мобильный лох

Ты
