### ISSUE TITLE
сделай гей мрумы с 10 челами, а не одним и мап мэйкер без защит

### ISSUE THREAD

**Issue by crceck123** [xeondev1337/OpenBrawl#13]
Надо (

**Comment by TheAcelot** [comment]
АХАХАХПХПХ

**Comment by crceck123** [comment]
> АХАХАХПХПХ

Яйцелот

**Comment by crceck123** [comment]
> АХАХАХПХПХ

Ты мне кста файлы на куриц должен

**Comment by TheAcelot** [comment]
> > АХАХАХПХПХ
> 
> Ты мне кста файлы на куриц должен

ты лох, сам не можешь наговнокодить

**Comment by crceck123** [comment]
> > > АХАХАХПХПХ
> > 
> > 
> > Ты мне кста файлы на куриц должен
> 
> ты лох, сам не можешь наговнокодить

Ты, я не умею грвнокодить
