### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by ghost** [xeondev1337/OpenBrawl#18]
I compiled the code and run Supercell.laser.server.dll but there is a problem with mongodb

**Comment by hehehehaa** [comment]
my question is where i have to put the link
![image](https://user-images.githubusercontent.com/110904928/183636657-6b9a247c-20c9-40c1-97fe-fad5e52ac26a.png)

**Comment by hehehehaa** [comment]
everything else works correctly
![image](https://user-images.githubusercontent.com/110904928/183637114-15f254c6-d8da-4eb3-bea3-edf8bc841f05.png)

**Comment by xeondev1337** [comment]
Why you use that cloud shit? Just install mongodb locally.

**Comment by xeondev1337** [comment]
and this server is deprecated btw. Use royale brawl instead.
