### ISSUE TITLE
help

### ISSUE THREAD

**Issue by terrawolf34** [xeondev1337/OpenBrawl#19]
In openbrawl I saw sussy file, and it says xeon is gay,is this true? please reply asap

**Comment by brownmouse10** [comment]
`True 100%`

**Comment by Lwitchy** [comment]
real

**Comment by xmooncoodex** [comment]
No, xeon is natural, and it's true. if he was gay, then he must be a negr, because only negrs are faggots. Xeon has a girlfriend. (btw, i fucked her)

**Comment by xmooncoodex** [comment]
Блять, ну я тебе сказал, что он натурал, какие ещё могут быть вопросы?
