### ISSUE TITLE
спасибо

### ISSUE THREAD

**Issue by ServerBSvvv** [xeondev1337/OpenBrawl#2]
топ серв спс)

**Comment by ServerBSvvv** [comment]
это самый лучший сервер в мире!

**Comment by zerobasa** [comment]
🤨

**Comment by CrCeck-f** [comment]
чел, тут только компом можно запускать, говно ебанное))

**Comment by ServerBSvvv** [comment]
ну да компом на сишарп сервера топ

**Comment by xeondev1337** [comment]
> чел, тут только компом можно запускать, говно ебанное))

а я чё виноват что ты мобильный гей

**Comment by ServerBSvvv** [comment]
согласен

**Comment by ServerBSvvv** [comment]
делаем вывод! CrCeck-f Мобильный гей!

**Comment by CrCeck-f** [comment]
> делаем вывод! CrCeck-f Мобильный гей!

сам ты эф!!!

**Comment by CrCeck-f** [comment]
> > чел, тут только компом можно запускать, говно ебанное))
> 
> а я чё виноват что ты мобильный гей

сам!!!

**Comment by CrCeck-f** [comment]
у меня ладитили 99484629573-₽84(#-4🟥2(₽- милиардаф в месятс залабатывают

**Comment by vanyadev228** [comment]
Pleljtfjrjfnnsrjjshhbjh python setup.py install

**Comment by KittenPro** [comment]
def writeInt(self, data, length=4):
        self.buffer += int(data).to_bytes(length, self.endian, signed=True)

**Comment by crceck123** [comment]
> > чел, тут только компом можно запускать, говно ебанное))
> 
> а я чё виноват что ты мобильный гей

ДА ТЫАХУЕЛ
