### ISSUE TITLE
Ничего себе! Я шокирован! партия гордиться вами 

### ISSUE THREAD

**Issue by SavokBS** [xeondev1337/OpenBrawl#3]
Кинь нюдсв пжпжржржржрж нюдсв кинь пжпжпжпжпжпжпжпж член пжпжпжпжпж

**Comment by zerobasa** [comment]
![Bebra](https://user-images.githubusercontent.com/72919306/145678327-c04785f3-14d2-46d3-a806-07776ed8aa3c.png)

**Comment by zerobasa** [comment]
Поставьте лайки

**Comment by zerobasa** [comment]
Етот png 1 мегабайт забрал

**Comment by CrCeck-f** [comment]
> `[хуй](хуй) `
